#!/bin/bash
# Examples of using the MineRL-NPV training and evaluation scripts

echo "🚀 MineRL-NPV Scripts Usage Examples"
echo "=================================="

echo ""
echo "📋 Prerequisites:"
echo "  - Install dependencies: pip install -r requirements.txt"
echo "  - Ensure sample data exists: mine_rl_npv/data/sample_model.csv"
echo ""

# Example 1: Basic headless training
echo "Example 1: Basic Training (Headless Mode)"
echo "----------------------------------------"
echo "python train_model.py \\"
echo "  --config examples/train_small.yaml \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --timesteps 1000"
echo ""

# Example 2: Training with visualization
echo "Example 2: Training with Visualization"
echo "-------------------------------------"
echo "python train_model.py \\"
echo "  --config examples/train_small.yaml \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --visualization \\"
echo "  --timesteps 1000"
echo ""

# Example 3: Custom training with GPU
echo "Example 3: Custom Training (GPU, Custom Output)"
echo "----------------------------------------------"
echo "python train_model.py \\"
echo "  --config examples/train_small.yaml \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --device cuda \\"
echo "  --timesteps 5000 \\"
echo "  --output-dir my_experiments/ \\"
echo "  --seed 42 \\"
echo "  --verbose 2"
echo ""

# Example 4: Basic evaluation
echo "Example 4: Basic Evaluation (Headless Mode)"
echo "------------------------------------------"
echo "python evaluate_model.py \\"
echo "  --model experiments/runs/minerl_npv_test_*/models/best_model.zip \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --episodes 10"
echo ""

# Example 5: Comprehensive evaluation with visualization
echo "Example 5: Comprehensive Evaluation with Visualization"
echo "----------------------------------------------------"
echo "python evaluate_model.py \\"
echo "  --model experiments/runs/minerl_npv_test_*/models/best_model.zip \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --visualization \\"
echo "  --episodes 20 \\"
echo "  --compare \\"
echo "  --plot \\"
echo "  --output detailed_evaluation/"
echo ""

# Example 6: Quick test run
echo "Example 6: Quick Test Run (Complete Pipeline)"
echo "--------------------------------------------"
echo "# Step 1: Quick training"
echo "python train_model.py \\"
echo "  --config examples/train_small.yaml \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --timesteps 500 \\"
echo "  --verbose 1"
echo ""
echo "# Step 2: Evaluate the trained model"
echo "python evaluate_model.py \\"
echo "  --model experiments/runs/minerl_npv_test_*/models/best_model.zip \\"
echo "  --data mine_rl_npv/data/sample_model.csv \\"
echo "  --episodes 5 \\"
echo "  --plot"
echo ""

echo "💡 Tips:"
echo "-------"
echo "  - Use 'examples/train_small.yaml' for testing (reduced memory requirements)"
echo "  - Use 'mine_rl_npv/configs/train.yaml' for full-scale training"
echo "  - Monitor training with: tensorboard --logdir experiments/runs"
echo "  - Use --headless for server environments"
echo "  - Use --visualization for interactive development"
echo "  - Check SCRIPTS_USAGE.md for detailed documentation"
echo ""

echo "🔧 Troubleshooting:"
echo "------------------"
echo "  - Memory errors: Use examples/train_small.yaml or reduce grid size"
echo "  - Import errors: Ensure you're in the repository root directory"
echo "  - GPU issues: Use --device cpu to force CPU usage"
echo "  - Display issues: Scripts auto-configure headless mode"
echo ""